---
kind: Service
apiVersion: v1
metadata:
  name: messaging-service
  labels:
    tier: msg
spec:
  type: ClusterIp
  selector:
    tier: msg
  ports:
    protocol: tcp
    port: 6379
    targetPort: 6379

