---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
spec:
  selector:
    matchLabels:
      app: kloud
  replicas: 2
  spec:
    container:
    - name: hr-web-app
      image: kodekloud/webapp-color
