---
apiVersion: apps/v1
kind: Pod
metadata:
  name: static-busybox
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kloud
  replicas: 2
  template:
    metadata:
      labels:
        app: kloud
    spec:
      containers:
      - name: hr-web-app
        image: kodekloud/webapp-color
