---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-1-claim
spec:
  capacity:
    storageClassName: manual
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: use-pv-roy
spec:
  volumes:
  - name: pv-1
    persistantVolumeClaim:
      claimName: pv-1-claim
  containers:
  - name: use-pv
    image: nginx
    resources: {}
    volumeMounts:
    - name: pv-1
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
