---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pv-roy
spec:
  containers:
  - name: use-pv
    image: nginx
    resources: {}
    volumeMounts:
    - name: redis-storage-roy
      mountPath: /data/redis
  volumes:
  - name: redis-storage-roy
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
