---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv-roy
  name: use-pv-roy
spec:
  volumes:
  - name: pv-1
    persistentVolumeClaim:
      claimName: pv-1
  containers:
  - name: use-pv-roy
    image: nginx
    resources: {}
    volumeMounts:
    - name: pv-1
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
