---
kind: Service 
apiVersion: v1
metadata:
  name: nginx-resolver-service
spec:
  selector:
    app: nginx
    name: busybox
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
    app: nginx
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    ports:
    - containerPort: 80
