apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webbapp
  name: webbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webbapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webbapp
    spec:
      containers:
      - image: nginx:1.17.1
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
